const os = require("os")
console.log(os.freemem())
console.log(os.homedir())
console.log(os.hostname())
console.log(os.endianness())
// console.log(os.getPriority([pid]))
console.log(os.loadavg())
console.log(os.networkInterfaces())
console.log(os.tmpdir())
console.log(os.type())
console.log(os.uptime())
